services:
  rust-app:
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile
    volumes:
      - .:/develop
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  cargo:
    build:
      context: .
      dockerfile: ./docker/cargo/Dockerfile
    working_dir: /develop
    volumes:
      - .:/develop
  trunk:
    build:
      context: .
      dockerfile: ./docker/trunk/Dockerfile
    working_dir: /develop
    volumes:
      - .:/develop
    ports:
      - "8080:8080"
    command: /bin/bash -c "trunk serve"
    stdin_open: true
    tty: true
